### ISSUE TITLE
WP81 and UWP support?

### ISSUE THREAD

**Issue by EmilAlipiev** [JamieMellway/iTextSharpLGPL-Monotouch#2]
Hi,

maybe a stupid question but I dont have any experience using itextsharp on xamarin. Before I start jumping into your library, does it not work for Windows and UWP? Does traditional itextsharp library already work for windows and uwp but not for android and ios? so we can mix them for different platforms. 

thanks for clearing it.

**Comment by JamieMellway** [comment]
I have not been able to get PDF generation on UWP to work with any library.   It does not work with iTextSharpLGPL or the commercial version.  I had the commercial Apitron.PDF.Kit working locally, but it would not deploy.  Apitron told me they fixed it, but the versions I tested still failed.  Maybe the latest build works.

If you get PDF generation working on UWP, I'd love to know.

**Comment by JamieMellway** [comment]
Oh, to your other question.  This library and the android version is just the iTextSharpLGPL library tweaked a little bit to run with Mono on those platforms.  It's here on github just so I comply with the LGPL.  With regular win32, use the iTextSharpLGPL library in NuGet or get the commercial license.  For UWP, wait until it is supported in the commercial version.
